import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { workflowFile, type Diagnostic } from '@mboss/core';
import type { CallToolResult } from '@modelcontextprotocol/server';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import type { Database } from '../debug/client.js';
import type {
  OperationOutputRow,
  WorkflowStatusRow,
} from '../debug/queries.js';
import type { ToolDefinition } from '../registry.js';
import {
  makeBuildableProject,
  makeFixtureProject,
  type ProjectFixture,
} from '../test-support/fixture-project.js';

import { projectBuild } from './project-build.js';
import { makeProjectDebug } from './project-debug.js';
import { makeProjectDeploy } from './project-deploy.js';
import { makeProjectTest } from './project-test.js';
import type { CommandRequest, CommandOutcome } from './run-command.js';

/**
 * The project tools against a real project in a
 * temp directory.
 *
 * `project_build` runs the real compiler and the
 * real type-check gate, because both are the
 * behaviour under test. The two tools that shell
 * out and the one that opens a database are given
 * their seam instead: what they are is a
 * well-formed command and a faithful reading of
 * what comes back, and neither needs Railway or
 * Postgres to be true.
 */

let fixture: ProjectFixture;

afterEach(() => {
  fixture.cleanup();
});

function call(
  tool: ToolDefinition,
  args: object = {},
): Promise<CallToolResult> {
  return tool.run(args, {
    projectDir: fixture.dir,
    mbossDir: fixture.mbossDir,
    proposedBy: 'the tests',
  });
}

async function output<T>(result: Promise<CallToolResult>): Promise<T> {
  const settled = await result;

  if (settled.isError === true) {
    throw new Error(
      `unexpected failure: ${JSON.stringify(settled.structuredContent)}`,
    );
  }

  return settled.structuredContent as T;
}

/** Writes a workflow document straight to disk. */
function writeWorkflow(name: string, nodes: object[]): void {
  writeFileSync(
    workflowFile(fixture.mbossDir, name),
    `${JSON.stringify(
      {
        $schema: 'https://mboss.dev/schemas/workflow-v1.json',
        version: 1,
        revision: 1,
        name,
        title: name,
        nodes,
        edges: [],
      },
      null,
      2,
    )}\n`,
    'utf8',
  );
}

const TRIGGER = {
  id: 'start',
  title: 'Start',
  kind: 'trigger',
  config: { mode: 'manual' },
};

type BuildOutput = {
  ok: boolean;
  codegenMs: number;
  diagnostics: Diagnostic[];
  unsupported: string[];
  tscErrors: string[];
};

describe('project_build', () => {
  beforeEach(() => {
    fixture = makeBuildableProject();
  });

  it('writes the generated workflows and reports how long codegen took', async () => {
    writeWorkflow('greet', [TRIGGER]);

    const built = await output<BuildOutput>(call(projectBuild));

    const generated = join(fixture.dir, 'src/workflows/greet.workflow.ts');
    expect(existsSync(generated)).toBe(true);
    expect(readFileSync(generated, 'utf8')).toContain(
      'GENERATED BY MBOSS — DO NOT EDIT.',
    );
    expect(existsSync(join(fixture.dir, 'src/workflows/index.ts'))).toBe(true);
    expect(built.codegenMs).toBeGreaterThanOrEqual(0);
  });

  it('gates on validation errors before type-checking', async () => {
    // Two triggers: a document that says something
    // that cannot be true, rather than one whose
    // work is unfinished.
    writeWorkflow('two_ways_in', [
      TRIGGER,
      { ...TRIGGER, id: 'other', title: 'Other' },
    ]);

    const built = await output<BuildOutput>(call(projectBuild));

    expect(built.ok).toBe(false);
    expect(built.diagnostics.map((found) => found.code)).toContain('V01');
    expect(built.diagnostics.some((found) => found.severity === 'error')).toBe(
      true,
    );
    // Nothing was type-checked: the code the check
    // would read was never regenerated.
    expect(built.tscErrors).toEqual([]);
  });

  it('reports a project that compiles and type-checks clean', async () => {
    const built = await output<BuildOutput>(call(projectBuild));

    expect(built).toMatchObject({
      ok: true,
      diagnostics: [],
      unsupported: [],
      tscErrors: [],
    });
    expect(existsSync(join(fixture.dir, 'src/workflows/index.ts'))).toBe(true);
  });

  it('surfaces type errors', async () => {
    mkdirSync(join(fixture.dir, 'lib'), { recursive: true });
    writeFileSync(
      join(fixture.dir, 'lib/broken.ts'),
      "export const count: number = 'not a number';\n",
      'utf8',
    );

    const built = await output<BuildOutput>(call(projectBuild));

    expect(built.ok).toBe(false);
    expect(built.diagnostics).toEqual([]);
    expect(built.tscErrors.join('\n')).toContain('lib/broken.ts');
  });
});

type TestOutput = {
  ok: boolean;
  passed: number;
  failed: number;
  outputTail: string;
};

/** A runner that records what it was asked to do. */
function fakeRunner(outcome: CommandOutcome): {
  run: (request: CommandRequest) => Promise<CommandOutcome>;
  calls: CommandRequest[];
} {
  const calls: CommandRequest[] = [];

  return {
    calls,
    run: (request) => {
      calls.push(request);

      return Promise.resolve(outcome);
    },
  };
}

const PASSING_RUN = [
  ' ✓ lib/greet.test.ts (5 tests) 12ms',
  '',
  ' Test Files  1 passed (1)',
  '      Tests  5 passed (5)',
  '',
].join('\n');

const FAILING_RUN = [
  ' ✓ lib/greet.test.ts (4 tests | 1 failed) 12ms',
  '',
  ' Test Files  1 failed (1)',
  '      Tests  1 failed | 4 passed (5)',
  '',
].join('\n');

describe('project_test', () => {
  beforeEach(() => {
    fixture = makeFixtureProject();
  });

  it("runs the project's own test script and reports the counts", async () => {
    const runner = fakeRunner({ ok: true, output: PASSING_RUN });

    const ran = await output<TestOutput>(call(makeProjectTest(runner.run)));

    expect(runner.calls).toEqual([
      { cwd: fixture.dir, command: expect.any(String), args: ['run', 'test'] },
    ]);
    expect(ran).toMatchObject({ ok: true, passed: 5, failed: 0 });
    expect(ran.outputTail).toContain('Tests  5 passed (5)');
  });

  it('passes a filter through to the test run', async () => {
    const runner = fakeRunner({ ok: true, output: PASSING_RUN });

    await call(makeProjectTest(runner.run), { filter: 'greet' });

    expect(runner.calls[0]?.args).toEqual(['run', 'test', '--', 'greet']);
  });

  it('reports what failed', async () => {
    const runner = fakeRunner({ ok: false, output: FAILING_RUN });

    const ran = await output<TestOutput>(call(makeProjectTest(runner.run)));

    expect(ran).toMatchObject({ ok: false, passed: 4, failed: 1 });
  });

  it('counts nothing when the run printed no summary', async () => {
    const runner = fakeRunner({
      ok: false,
      output: 'npm error missing script',
    });

    const ran = await output<TestOutput>(call(makeProjectTest(runner.run)));

    expect(ran).toMatchObject({ ok: false, passed: 0, failed: 0 });
    expect(ran.outputTail).toContain('missing script');
  });

  it('keeps only the tail of a long run', async () => {
    const lines = Array.from({ length: 400 }, (_, at) => `line ${at}`);
    const runner = fakeRunner({ ok: true, output: lines.join('\n') });

    const ran = await output<TestOutput>(call(makeProjectTest(runner.run)));

    expect(ran.outputTail).toContain('line 399');
    expect(ran.outputTail).not.toContain('line 0\n');
    expect(ran.outputTail.split('\n').length).toBeLessThanOrEqual(50);
  });
});

type DeployOutput = { ok: boolean; outputTail: string };

describe('project_deploy', () => {
  beforeEach(() => {
    fixture = makeFixtureProject();
  });

  it("runs the project's own deploy script and reports its tail", async () => {
    const runner = fakeRunner({ ok: true, output: 'Deployed.\n' });

    const deployed = await output<DeployOutput>(
      call(makeProjectDeploy(runner.run)),
    );

    expect(runner.calls).toEqual([
      {
        cwd: fixture.dir,
        command: expect.any(String),
        args: ['run', 'deploy'],
      },
    ]);
    expect(deployed).toEqual({ ok: true, outputTail: 'Deployed.' });
  });

  it('reports a deploy that failed', async () => {
    const runner = fakeRunner({ ok: false, output: 'No linked project.\n' });

    const deployed = await output<DeployOutput>(
      call(makeProjectDeploy(runner.run)),
    );

    expect(deployed.ok).toBe(false);
    expect(deployed.outputTail).toContain('No linked project.');
  });
});

const RUN_ROW: WorkflowStatusRow = {
  workflow_uuid: 'wf-1',
  name: 'groom_booking',
  status: 'SUCCESS',
  recovery_attempts: '1',
  created_at: '1756684800000',
  completed_at: '1756684802500',
};

const STEP_ROW: OperationOutputRow = {
  function_id: 1,
  function_name: 'findSlot',
  started_at_epoch_ms: '1756684800100',
  completed_at_epoch_ms: '1756684800400',
  error: null,
  child_workflow_id: null,
};

/** A database that answers with the rows it is given. */
function fakeDatabase(answers: unknown[][]): {
  open: () => Promise<Database>;
  asked: { text: string; values: unknown[] }[];
  closed: () => number;
} {
  const asked: { text: string; values: unknown[] }[] = [];
  let closes = 0;

  return {
    asked,
    closed: () => closes,
    open: () =>
      Promise.resolve({
        query: <R>(text: string, values: unknown[]) => {
          asked.push({ text, values });

          return Promise.resolve((answers[asked.length - 1] ?? []) as R[]);
        },
        close: () => {
          closes += 1;

          return Promise.resolve();
        },
      }),
  };
}

type DebugOutput = {
  runs: {
    workflowId: string;
    name: string;
    status: string;
    recoveryAttempts: number;
    startedAt: string;
    durationMs?: number;
    steps?: object[];
  }[];
};

describe('project_debug', () => {
  beforeEach(() => {
    fixture = makeFixtureProject();
  });

  it('answers with the recent runs', async () => {
    const db = fakeDatabase([[RUN_ROW]]);

    const seen = await output<DebugOutput>(call(makeProjectDebug(db.open)));

    expect(seen).toEqual({
      runs: [
        {
          workflowId: 'wf-1',
          name: 'groom_booking',
          status: 'SUCCESS',
          recoveryAttempts: 1,
          startedAt: '2025-09-01T00:00:00.000Z',
          durationMs: 2500,
        },
      ],
    });
    expect(db.asked).toHaveLength(1);
    expect(db.asked[0]?.values).toEqual([10]);
  });

  it('answers with a named run and its steps', async () => {
    const db = fakeDatabase([[RUN_ROW], [STEP_ROW]]);

    const seen = await output<DebugOutput>(
      call(makeProjectDebug(db.open), { runId: 'wf-1' }),
    );

    expect(db.asked.map((query) => query.values)).toEqual([['wf-1'], ['wf-1']]);
    expect(seen.runs[0]?.steps).toEqual([
      {
        functionID: 1,
        name: 'findSlot',
        startedAtEpochMs: 1756684800100,
        completedAtEpochMs: 1756684800400,
      },
    ]);
  });

  it('asks for no steps when the named run is gone', async () => {
    const db = fakeDatabase([[]]);

    const seen = await output<DebugOutput>(
      call(makeProjectDebug(db.open), { runId: 'gone' }),
    );

    expect(seen.runs).toEqual([]);
    expect(db.asked).toHaveLength(1);
  });

  it('closes the connection it opened', async () => {
    const db = fakeDatabase([[RUN_ROW]]);

    await call(makeProjectDebug(db.open));

    expect(db.closed()).toBe(1);
  });

  it('closes the connection when the read fails', async () => {
    const open = () =>
      Promise.resolve<Database>({
        query: () => Promise.reject(new Error('relation does not exist')),
        close: () => {
          closes += 1;

          return Promise.resolve();
        },
      });
    let closes = 0;

    await expect(call(makeProjectDebug(open))).rejects.toThrow(
      /relation does not exist/,
    );
    expect(closes).toBe(1);
  });

  it('refuses to ask for more than fifty runs', () => {
    const db = fakeDatabase([[RUN_ROW]]);

    // The cap is on the input, so the refusal
    // happens before anything opens a connection.
    expect(() => call(makeProjectDebug(db.open), { limit: 51 })).toThrow(/50/);
    expect(db.asked).toHaveLength(0);
  });
});
